language: python

python:
  - 3.4

install:
  - sudo apt-get update -q
  - sudo apt-get install pandoc -y
  - sudo apt-get install redis-server
  - pip install -r requirements.txt
  - pip install pep8

script:
  - env PYTHONPATH=`pwd` python3 bin/test/runtests.py
  - env PYTHONPATH=`pwd` python3 gits/test/capabilities_test.py
  - pep8 bin/server.py gits/terminal.py gits/test/*
