language: python

python:
  - 3.4

install:
  - pip install -r requirements.txt
  - pip install pep8

script:
  - env PYTHONPATH=`pwd` python3 gits/test/capabilities_test.py
  - pep8 bin/server.py gits/terminal.py gits/test/*
