name: Linter Runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Run linter

    runs-on: ubuntu-latest

    env:
      SECRET_KEY: secret
      DJANGO_SETTINGS_MODULE: orion.settings

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint
        run: |
          find -name "*.py" -not -path "./.git/*" -not -path "./src/*" | xargs pylint --max-line-length=100 --disable=too-many-instance-attributes
